# This file relates to internal XMOS infrastructure and should be ignored by external users

lib_name: lib_board_support
project: '{{lib_name}}'
title: '{{lib_name}}: XMOS board support'
version: 1.1.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/lib_board_support.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-015142-UG
  doxygen_projects:
    lib_board_support:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_board_support.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-015141-SM
